my_string=input('Введите произвольный текст: ')
print('считаем количество введенных символов:' , len(my_string))
print('выводим текст в верхнем регистре: ' , my_string.upper())
print('выводим текст в нижнем регистре: ' , my_string.lower())
print('убиваем все пробелы: ' , my_string.replace(' ',''))
print('выводим первый символ строки:' , my_string[0])
print('выводим последний символ строки:' , my_string[-1])